# Site settings
title: Kei's Blog
header-img: img/home-bg.jpg
email: scauwjh@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://keiwu.me"
twitter_username: none
github_username:  scauwjh
facebook_username:  none

# Build settings
# markdown: kramdown
# highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
