# Site settings
title: Kei's Blog
header-img: img/home-bg.jpg
email: scauwjh@gmail.com
description: "blog for kei"
baseurl: ""
url: "http://keiwu.me"
twitter_username: none
github_username:  scauwjh
facebook_username:  none

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

pygments:    true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough","superscript"]
  
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
